server:
  port: 9909

spring:
  datasource:
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 1
        minIdle: 3
        maxActive: 100
        # 配置获取连接等待超时的时间
        maxWait: 6000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 1000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      primary: mysql #设置默认的数据源或者数据源组
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/dcytest?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: dcydemm123
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        pg:
          url: jdbc:postgresql://116.204.121.151:5432/idoc_zero_code
          username: postgres
          password: Cloudcmdi@2021
          driver-class-name: org.postgresql.Driver
          type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: cn.zing.dynamic.datasource.demo1.bean
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml